/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.app.cri;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiC;
import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.view.TiCompositeLayout;
import org.appcelerator.titanium.view.TiCompositeLayout.LayoutArrangement;
import org.appcelerator.titanium.view.TiUIView;

import com.noor.tests.ProgressIndicatorView;

import android.app.Activity;
import android.content.res.Resources;
import android.widget.Button;
import android.widget.TextView;


// This proxy can be created by calling Customresourceintegration.createExample({message: "hello world"})
@Kroll.proxy(creatableInModule=CustomresourceintegrationModule.class)
public class ExampleProxy extends TiViewProxy
{
	// Standard Debugging variables
	private static final String TAG = "ExampleProxy";

	private class ExampleView extends TiUIView
	{
		public ExampleView(TiViewProxy proxy) {
			super(proxy);
			LayoutArrangement arrangement = LayoutArrangement.DEFAULT;

			if (proxy.hasProperty(TiC.PROPERTY_LAYOUT)) {
				String layoutProperty = TiConvert.toString(proxy.getProperty(TiC.PROPERTY_LAYOUT));
				if (layoutProperty.equals(TiC.LAYOUT_HORIZONTAL)) {
					arrangement = LayoutArrangement.HORIZONTAL;
				} else if (layoutProperty.equals(TiC.LAYOUT_VERTICAL)) {
					arrangement = LayoutArrangement.VERTICAL;
				}
			}
			setNativeView(new TiCompositeLayout(proxy.getActivity(), arrangement));
		}

		@Override
		public void processProperties(KrollDict d)
		{
			super.processProperties(d);
		}
	}

	// Constructor
	public ExampleProxy()
	{
		super();
	}

	@Override
	public TiUIView createView(final Activity activity)
	{			
				class MyImageView extends TiUIView 
				{

					public MyImageView(TiViewProxy proxy) 
					{
						super(proxy);

						Button label = new Button(activity);  
					    label.setText("My Label");  
					    label.setTextSize(20);  
					    
						String packageName = activity.getPackageName();
						Resources resources = activity.getResources();
						int textStyle = resources.getIdentifier("com_facebook_loginbutton_blue", "drawable", packageName);
					    label.setBackgroundResource(textStyle);
						
						setNativeView(label);
					}
					
					@Override
					public void processProperties(KrollDict d)
					{
						super.processProperties(d);
					}
					
				}
				
				MyImageView imageView = new MyImageView(this);
				return imageView;
	}

	// Handle creation options
	@Override
	public void handleCreationDict(KrollDict options)
	{
		super.handleCreationDict(options);
		
		if (options.containsKey("message")) {
			Log.d(TAG, "example created with message: " + options.get("message"));
		}
	}
	
	// Methods
	@Kroll.method
	public void printMessage(String message)
	{
		Log.d(TAG, "printing message: " + message);
	}


	@Kroll.getProperty @Kroll.method
	public String getMessage()
	{
        return "Hello World from my module";
	}

	@Kroll.setProperty @Kroll.method
	public void setMessage(String message)
	{
	    Log.d(TAG, "Tried setting module message to: " + message);
	}
}